#!/usr/bin/bash

RUNNING=NO
if [ "$(ps -a | grep [s]sh-agent)" ]; then
  RUNNING=YES
fi

if [ "$1" = "-k" ]; then
  if [ $RUNNING = "YES" ]; then
    . ~/.ssh_agent_vars
    ssh-agent -k
  else
    echo "No ssh-agent process"
  fi
  echo "echo no agent" > ~/.ssh_agent_vars
  exit
fi

if [ $RUNNING = "YES" ]; then 
  echo "Agent already running"
  . ~/.ssh_agent_vars
else
  ssh-agent > ~/.ssh_agent_vars
  . ~/.ssh_agent_vars

  ssh-add

  echo "Wrote to . ~/.ssh_agent_vars"
  #echo "SSH agent variables are not set in this shell"
  #echo "reccomend sourcing . ~/.ssh_agent_vars"
  #echo "or exititing ..."
fi

